# .github/workflows/deploy.yml
name: Deploy
on: 
  push:
    branches:
      - main
    path:
      - /charts/goquorum-node

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'nginx'
        namespace: 'default'
        chart: '/charts/goquorum-node'
        token: '${{ github.token }}'
        value-files: >-
        [
          "values.yaml"
        ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
