on:
  workflow_dispatch:
    inputs:
      k8s_cluster:
        description: 'cluster k8s to be deployed on'
        required: true
        default: 'dev'
      var_file:
        description: 'value file going to use'
        required: true
        default: 'values.yml'
      namespace:
        description: 'namespace going to deploy'
        required: true
        default: 'quorum'
      image_tag:
        description: 'image tag to deploy'
        required: true
        default: 'v1.1.1'
      chart_deploy:
        description: 'which chart to be deployed'
        required: true
        default: 'goquorum-node'
      dry_run:
        description: 'show result'
        required: true
        default: 'false'         
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Create kube config
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          chmod 600 $HOME/.kube/config
          kubectl get node
      - name: Install helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
      - name: Lint helm charts
        run: helm lint ./charts/${{ github.event.inputs.chart_deploy }}/
      - name: Deploy
        run: |
          helm upgrade --install  ./charts/${{ github.event.inputs.chart_deploy }}/ -f ./charts/${{ github.event.inputs.chart_deploy }}/${{ github.event.inputs.var_file }} \
            --namespace ${{ github.event.inputs.namespace }} --create-namespace \
            --set image.tag=${{ github.event.inputs.image_tag }}
